language: node_js
os: linux
node_js: 8

jobs:
  include:

  - stage: test
    install: npm install --only=dev
    script: npm test

  - stage: release
    script: npm version minor
    after_script: git push; git push --tags
    if: branch = release

  - stage: hotfix
    script: npm version patch
    after_script: git push
    if: branch = hotfix

  - stage: deploy
    deploy:
      provider: npm
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
      skip_cleanup: true
      on:
        branch: master
        repo: jasperes/npm-test

notifications:
  email: false

