language: node_js
os: linux
node_js: 8

jobs:
  include:

  - stage: test
    install: npm install --only=dev
    script: npm test

  - stage: deploy
    deploy:
      provider: npm
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
      skip_cleanup: true
      on:
        branch: master
        repo: jasperes/npm-test

notifications:
  email:
    on_success: never

